
USE MASTER
DROP DATABASE IF EXISTS Airport_DB

CREATE DATABASE Airport_DB
ON(
	NAME = Airport,
	FILENAME = 'D:\_IPPT\DIPLOMA\DATABASE\AIRPORT.MDF',
	SIZE =8192KB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 65536KB)
LOG ON(
	NAME = Airport_LOG,
	FILENAME = 'd:\_ippt\diploma\database\airport_log.ldf',
	SIZE =10,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 65536KB)

USE Airport_DB


GO
DROP TABLE IF EXISTS SPERSON.EMAIL
DROP TABLE IF EXISTS SPERSON.NUMBER
DROP TABLE IF EXISTS AIRCRAFT
DROP TABLE IF EXISTS SFLIGHT.FLIGHT_EMERGENCY
DROP TABLE IF EXISTS SFLIGHT.TICKET
DROP TABLE IF EXISTS SPERSON.PERSON
DROP TABLE IF EXISTS SFLIGHT.FLIGHT
DROP TABLE IF EXISTS SAIRPORT.AIRPORT
DROP TABLE IF EXISTS SAIRPORT.AIRLINE

GO
DROP SCHEMA IF EXISTS SFLIGHT
DROP SCHEMA IF EXISTS SAIRPORT
DROP SCHEMA IF EXISTS SPERSON

GO
DROP VIEW IF EXISTS VPERSON
DROP VIEW IF EXISTS VTRIP
DROP VIEW IF EXISTS VEMERGENCYFLIGHTS

GO
CREATE SCHEMA SPERSON
GO


CREATE TABLE SPERSON.PERSON
(
    ID INT IDENTITY CONSTRAINT PK_PERSON_ID PRIMARY KEY,
    FIRST_NAME VARCHAR(40) NOT NULL,
    MIDDLE_NAME VARCHAR(40) NULL,
    LAST_NAME VARCHAR(40) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN('F','M')) NULL,
    MOFIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE SPERSON.EMAIL
(
    EMAIL VARCHAR(255) NOT NULL CHECK(EMAIL LIKE '%@%.%') CONSTRAINT PK_EMAIL PRIMARY KEY,
    PERSON_ID INT CONSTRAINT FK_PERSON_EMAIL_ID FOREIGN KEY REFERENCES SPERSON.PERSON(ID),
    ISACTIVE BIT NOT NULL DEFAULT 1,
    MOFIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE SPERSON.NUMBER
(
    NUMBER VARCHAR(15) CONSTRAINT PK_NUMBER PRIMARY KEY NONCLUSTERED,
    PERSON_ID INT CONSTRAINT FK_PERSON_NUMBER_ID FOREIGN KEY REFERENCES SPERSON.PERSON(ID),
    ISACTIVE BIT NOT NULL DEFAULT 1,
    MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
)


GO
CREATE SCHEMA SAIRPORT
GO

CREATE TABLE SAIRPORT.AIRPORT
(
	IATA VARCHAR(5) PRIMARY KEY,
    ICAO VARCHAR(5),
    NAME VARCHAR(100),
    LATITUDE_DEG DECIMAL(18,16),
    LONGITUDE_DEG DECIMAL(19,16),
    ELEVATION_FT SMALLINT,
    CONTINENT VARCHAR(4),
    ISO_COUNTRY VARCHAR(10),
    COUNTRY_NAME VARCHAR(100),
    ISO_REGION VARCHAR(10),	
    REGION_NAME VARCHAR(100),
    MUNICIPALITY VARCHAR(100)
)


CREATE TABLE SAIRPORT.AIRLINE
(
    [IATA] VARCHAR(5),
    [ICAO] VARCHAR(5),
    [CALLSIGN] VARCHAR(50),
    [COUNTRY] VARCHAR(50),
    [AIRLINE] VARCHAR(50),
    ISACTIVE BIT NULL DEFAULT 1,
    MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
)

GO
CREATE SCHEMA SFLIGHT
GO

CREATE TABLE SFLIGHT.FLIGHT(
    [FLIGHT_NUMBER] INT PRIMARY KEY,
	[FLIGHT_DATE] DATE,
    [AIRLINE] VARCHAR(5),
    [TAIL_NUMBER] VARCHAR(10),
    [ORIGIN_AIRPORT] VARCHAR(5) FOREIGN KEY REFERENCES SAIRPORT.AIRPORT([IATA]),
    [DESTINATION_AIRPORT] VARCHAR(5) FOREIGN KEY REFERENCES SAIRPORT.AIRPORT([IATA]),
    [SCHEDULED_DEPARTURE] VARCHAR(6),
    [DEPARTURE_TIME] VARCHAR(6),
    [DEPARTURE_DELAY] VARCHAR(6),
    [TAXI_OUT] VARCHAR(6),
    [WHEELS_OFF] VARCHAR(6),
    [SCHEDULED_TIME] VARCHAR(6),
    [ELAPSED_TIME] VARCHAR(6),
    [AIR_TIME] VARCHAR(6),
    [DISTANCE] VARCHAR(6),
    [WHEELS_ON] VARCHAR(6),
    [TAXI_IN] VARCHAR(6),
    [SCHEDULED_ARRIVAL] VARCHAR(6),
    [ARRIVAL_TIME] VARCHAR(6),
    [ARRIVAL_DELAY] VARCHAR(6)
)

CREATE TABLE SFLIGHT.FLIGHT_EMERGENCY(
    [FLIGHT_NUMBER] INT FOREIGN KEY REFERENCES SFLIGHT.FLIGHT([FLIGHT_NUMBER]),
    [DIVERTED] VARCHAR(2),
    [CANCELLED] VARCHAR(2),
    [CANCELLATION_REASON] VARCHAR(20),
    [AIR_SYSTEM_DELAY] VARCHAR(9),
    [SECURITY_DELAY] VARCHAR(9),
    [AIRLINE_DELAY] VARCHAR(9),
    [LATE_AIRCRAFT_DELAY] VARCHAR(9),
    [WEATHER_DELAY] VARCHAR(9)
)


CREATE TABLE AIRCRAFT
(
    [TAIL_NUMBER] VARCHAR(10),
	NAME VARCHAR(100),
	AIRLINE VARCHAR(100),
	OPERATOR VARCHAR(100),
	TYPE_CODE VARCHAR(10),
	CODE VARCHAR(10),
	MODE_S VARCHAR(10),
    MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
)


CREATE TABLE SFLIGHT.TICKET(
	ID INT PRIMARY KEY IDENTITY,
    [FLIGHT_NUMBER] INT,-- FOREIGN KEY REFERENCES SFLIGHT.FLIGHT([FLIGHT_NUMBER]),
    PERSON_ID INT CONSTRAINT FK_PERSON_EMAIL_ID FOREIGN KEY REFERENCES SPERSON.PERSON(ID),
	SEAT VARCHAR(3),
	PRICE MONEY
)


GO
CREATE VIEW VPERSON 
AS 
SELECT TOP 50 
	[ID], [FIRST_NAME], [MIDDLE_NAME], [LAST_NAME], [DATE_OF_BIRTH],
	[GENDER],[NUMBER], [MODIFIED_DATE] [EMAIL] 
FROM SPERSON.PERSON P
INNER JOIN SPERSON.NUMBER N
ON N.PERSON_ID = P.ID 
INNER JOIN SPERSON.EMAIL E
ON E.PERSON_ID = P.ID

GO
CREATE VIEW VEMERGENCYFLIGHTS
AS 
SELECT TOP 50 
	F.[FLIGHT_NUMBER], FLIGHT_DATE, [AIRLINE], [TAIL_NUMBER], [ORIGIN_AIRPORT],
	[DESTINATION_AIRPORT], [SCHEDULED_DEPARTURE], [DEPARTURE_TIME], [DEPARTURE_DELAY], [TAXI_OUT], [WHEELS_OFF], [SCHEDULED_TIME],
	[ELAPSED_TIME], [AIR_TIME], [DISTANCE], [WHEELS_ON], [TAXI_IN], [SCHEDULED_ARRIVAL], [ARRIVAL_TIME], [ARRIVAL_DELAY],
	[DIVERTED], [CANCELLED], [CANCELLATION_REASON], [AIR_SYSTEM_DELAY], [SECURITY_DELAY], [AIRLINE_DELAY], [LATE_AIRCRAFT_DELAY], [WEATHER_DELAY]
FROM SFLIGHT.FLIGHT F
RIGHT JOIN SFLIGHT.FLIGHT_EMERGENCY E
ON E.FLIGHT_NUMBER = F.FLIGHT_NUMBER

GO
CREATE VIEW VTRIP
AS SELECT TOP 50
	FLIGHT_DATE, A1.NAME AS ORIGIN_NAME,
	A1.COUNTRY_NAME AS ORIGIN_COUNTRY , A2.NAME AS DESTINATION_NAME,
	A2.COUNTRY_NAME AS DESTINATION_COUNTRY,
	AR.CALLSIGN AS AIRLINE_NAME
FROM SFLIGHT.FLIGHT F
LEFT JOIN SAIRPORT.AIRPORT A1 
ON F.ORIGIN_AIRPORT= A1.ICAO
LEFT JOIN SAIRPORT.AIRPORT A2 
ON F.DESTINATION_AIRPORT= A2.ICAO
LEFT JOIN SAIRPORT.AIRLINE AR 
ON F.AIRLINE= AR.AIRLINE