USE Airport_DB

ALTER TABLE SPERSON.PERSON
ADD CONSTRAINT pk_PERSON_ID PRIMARY KEY(PERSON_ID)

ALTER TABLE SPERSON.EMAIL
ADD CONSTRAINT EMAIL PRIMARY KEY NONCLUSTERED(EMAIL) 

ALTER TABLE SPERSON.EMAIL
ADD CONSTRAINT fk_PERSON_EMAIL_ID FOREIGN KEY(PERSON_ID) REFERENCES SPERSON.PERSON(ID)

ALTER TABLE SPERSON.NUMBER
ADD CONSTRAINT PK_NUMBER PRIMARY KEY NONCLUSTERED(NUMBER)

ALTER TABLE SPERSON.NUMBER
ADD CONSTRAINT pk_IATA PRIMARY KEY (IATA)

ALTER TABLE SAIRPORT.NUMBER
ADD CONSTRAINT fk_PERSON_NUMBER_ID FOREIGN KEY REFERENCES SPERSON.PERSON(ID)



ALTER TABLE SAIRPORT.AIRPORT
ADD CONSTRAINT pk_IATA PRIMARY KEY (IATA)

ALTER TABLE SFLIGHT.FLIGHT
ADD CONSTRAINT pk_IATA PRIMARY KEY ([FLIGHT_NUMBER])

ALTER TABLE SFLIGHT.FLIGHT
ADD CONSTRAINT fk_ORIGIN FOREIGN KEY(ORIGIN_AIRPORT) REFERENCES SAIRPORT.AIRPORT([IATA])

ALTER TABLE SFLIGHT.FLIGHT
ADD CONSTRAINT fk_AIRLINE FOREIGN KEY(AIRLINE) REFERENCES SAIRPORT.AIRLINE(IATA)

ALTER TABLE SFLIGHT.FLIGHT
ADD CONSTRAINT fk_TAIL_NUMBER FOREIGN KEY(TAIL_NUMBER) REFERENCES AIRCRAFT(TAIL_NUMBER)

ALTER TABLE SFLIGHT.FLIGHT
ADD CONSTRAINT fk_DESTINATION FOREIGN KEY(DESTINATION_AIRPORT) REFERENCES SAIRPORT.AIRPORT([IATA])

ALTER TABLE SFLIGHT.FLIGHT_EMERGENCY
ADD CONSTRAINT fk_FLIGHT_NUMBER FOREIGN KEY(FLIGHT_NUMBER) REFERENCES SFLIGHT.FLIGHT(FLIGHT_NUMBER)

ALTER TABLE SFLIGHT.TICKET
ADD CONSTRAINT fk_FLIGHT_NUMBER FOREIGN KEY(PERSON_ID) REFERENCES SPERSON.PERSON(ID),

ALTER TABLE SFLIGHT.TICKET
ADD CONSTRAINT fk_PERSON_ID FOREIGN KEY(FLIGHT_NUMBER) REFERENCES SFLIGHT.FLIGHT([FLIGHT_NUMBER]),




GO
CREATE VIEW VPERSON 
AS 
SELECT TOP 50 
	[ID], [FIRST_NAME], [MIDDLE_NAME], [LAST_NAME], [DATE_OF_BIRTH],
	[GENDER],[NUMBER], [MODIFIED_DATE] [EMAIL] 
FROM SPERSON.PERSON P
INNER JOIN SPERSON.NUMBER N
ON N.PERSON_ID = P.ID 
INNER JOIN SPERSON.EMAIL E
ON E.PERSON_ID = P.ID

GO
CREATE VIEW VEMERGENCYFLIGHTS
AS 
SELECT TOP 50 
	F.[FLIGHT_NUMBER], FLIGHT_DATE, [AIRLINE], [TAIL_NUMBER], [ORIGIN_AIRPORT],
	[DESTINATION_AIRPORT], [SCHEDULED_DEPARTURE], [DEPARTURE_TIME], [DEPARTURE_DELAY], [TAXI_OUT], [WHEELS_OFF], [SCHEDULED_TIME],
	[ELAPSED_TIME], [AIR_TIME], [DISTANCE], [WHEELS_ON], [TAXI_IN], [SCHEDULED_ARRIVAL], [ARRIVAL_TIME], [ARRIVAL_DELAY],
	[DIVERTED], [CANCELLED], [CANCELLATION_REASON], [AIR_SYSTEM_DELAY], [SECURITY_DELAY], [AIRLINE_DELAY], [LATE_AIRCRAFT_DELAY], [WEATHER_DELAY]
FROM SFLIGHT.FLIGHT F
RIGHT JOIN SFLIGHT.FLIGHT_EMERGENCY E
ON E.FLIGHT_NUMBER = F.FLIGHT_NUMBER

GO
CREATE VIEW VTRIP
AS SELECT TOP 50
	FLIGHT_DATE, A1.NAME AS ORIGIN_NAME,
	A1.COUNTRY_NAME AS ORIGIN_COUNTRY , A2.NAME AS DESTINATION_NAME,
	A2.COUNTRY_NAME AS DESTINATION_COUNTRY,
	AR.CALLSIGN AS AIRLINE_NAME
FROM SFLIGHT.FLIGHT F
LEFT JOIN SAIRPORT.AIRPORT A1 
ON F.ORIGIN_AIRPORT= A1.ICAO
LEFT JOIN SAIRPORT.AIRPORT A2 
ON F.DESTINATION_AIRPORT= A2.ICAO
LEFT JOIN SAIRPORT.AIRLINE AR 
ON F.AIRLINE= AR.AIRLINE